version: "3.9"

x-default-env: &spring-prod
  SPRING_PROFILES_ACTIVE: prod
  # Production profile expects DB_HOST, DB_PORT, DB_NAME (not DB_URL)
  DB_HOST: postgres
  DB_PORT: 5432
  DB_NAME: shopifake_test
  DB_USERNAME: testuser
  DB_PASSWORD: testpass
  PORT: 8080
  # CORS settings for production
  CORS_ALLOWED_ORIGINS: "*"
  CORS_ALLOW_CREDENTIALS: "true"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: shopifake_test
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser"]
      interval: 5s
      timeout: 3s
      retries: 5

  bus:
    image: shopifake-bus:test-local
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: testuser
      RABBITMQ_DEFAULT_PASS: testpass
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Application services
  # Note: Images will be overridden by CI workflow with GHCR images from the lock
  gateway:
    image: shopifake-gateway:test-local
    environment:
      <<: *spring-prod
      SERVICES_ACCESS_URL: http://access:8080
      SERVICES_AUDIT_URL: http://audit:8080
      SERVICES_CATALOG_URL: http://catalog:8080
      SERVICES_CUSTOMERS_URL: http://customers:8080
      SERVICES_INVENTORY_URL: http://inventory:8080
      SERVICES_ORDERS_URL: http://orders:8080
      SERVICES_PRICING_URL: http://pricing:8080
      SERVICES_RECOMMENDER_URL: http://recommender:8000
      SERVICES_SALES_DASHBOARD_URL: http://sales-dashboard:8080
      SERVICES_SITES_URL: http://sites:8080
      SERVICES_CHATBOT_URL: http://chatbot:8000
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      bus:
        condition: service_healthy
      access:
        condition: service_healthy
      audit:
        condition: service_healthy
      catalog:
        condition: service_healthy
      customers:
        condition: service_healthy
      inventory:
        condition: service_healthy
      orders:
        condition: service_healthy
      pricing:
        condition: service_healthy
      sales-dashboard:
        condition: service_healthy
      sites:
        condition: service_healthy
      chatbot:
        condition: service_healthy
      recommender:
        condition: service_healthy
      auth-b2c:
        condition: service_healthy
      auth-b2e:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  access:
    image: shopifake-access:test-local
    environment:
      <<: *spring-prod
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  audit:
    image: shopifake-audit:test-local
    environment:
      <<: *spring-prod
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  catalog:
    image: shopifake-catalog:test-local
    environment:
      <<: *spring-prod
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  customers:
    image: shopifake-customers:test-local
    environment:
      <<: *spring-prod
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  inventory:
    image: shopifake-inventory:test-local
    environment:
      <<: *spring-prod
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  orders:
    image: shopifake-orders:test-local
    environment:
      <<: *spring-prod
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  pricing:
    image: shopifake-pricing:test-local
    environment:
      <<: *spring-prod
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  sales-dashboard:
    image: shopifake-sales-dashboard:test-local
    environment:
      <<: *spring-prod
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  sites:
    image: shopifake-sites:test-local
    environment:
      <<: *spring-prod
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  chatbot:
    image: shopifake-chatbot:test-local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  recommender:
    image: shopifake-recommender:test-local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-b2c:
    image: shopifake-auth-b2c:test-local
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://testuser:testpass@postgres:5432/shopifake_test
      BETTER_AUTH_SECRET: test-secret-key-for-development-only-min-32-chars
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-b2e:
    image: shopifake-auth-b2e:test-local
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://testuser:testpass@postgres:5432/shopifake_test
      BETTER_AUTH_SECRET: test-secret-key-for-development-only-min-32-chars
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

