name: CI Dev Pull Request

on:
  pull_request:
    branches:
      - staging
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  actions: read

jobs:
  integration_tests:
    name: System & Integration Tests
    uses: ./.github/workflows/system-tests.yml
    with:
      compose-file: compose/system-tests.compose.yml
      integration-command: bash scripts/tests/run-integration-tests.sh
      system-command: bash scripts/tests/run-system-tests.sh

  generate_lock:
    name: Generate Lock
    needs: integration_tests
    uses: ./.github/workflows/generate-lock.yml
    with:
      lock-artifact-name: lock-${{ github.event.number }}
      lock-filename: lock-pr-${{ github.event.number }}.yml

  publish_lock:
    name: Publish Lock Summary
    needs: generate_lock
    uses: ./.github/workflows/publish-lock.yml
    with:
      lock-artifact-name: lock-${{ github.event.number }}
      lock-filename: lock-pr-${{ github.event.number }}.yml

